- name: install mariadb package (CentOS)
  tags: mariadb,centos,db
  yum:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu)
  tags: mariadb,db,ubuntu 
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
